"""Add employee location table

Revision ID: 16d51ba27b24
Revises: 
Create Date: 2022-07-29 13:46:49.664562

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16d51ba27b24"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.String(length=30), nullable=True),
        sa.Column("longitude", sa.String(length=30), nullable=True),
        sa.Column("inserted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee_location")
    # ### end Alembic commands ###
